```{r remove_uneeded_params}
# remove uneeded parameters
df <- df[,apply(df, 2, function(x) { length(unique(x)) > 1 })]
```

**Parameters tested:**

```{r params_tested_pathogen}
table(df$network_type)
table(df$cpm_transform)
table(df$log2_transform)
table(df$quantile_normalize)
table(df$batch_adjustment)
table(df$similarity_measure)
table(df$topological_overlap)
table(df$adj_power)
```

```{r extend_human_results}
# score <- ratio of supported weights * 1000
df$iref_score <- (df$irefindex_edge_weight / df$total_edge_weight) * 1000

# total enrichment
df$total_enriched <- df$go_total_enriched + df$kegg_total_enriched +
                     df$cpdb_total_enriched + df$marbach_total_enriched
df$total_enriched_unique <- df$unique_go_terms + df$unique_kegg_terms +
                           df$unique_cpdb_terms + df$unique_marbach_terms

df$enrichment_score <- as.vector(1/3 * (scale(df$total_go_pval) +
                                        scale(df$total_cpdb_pval) + 
                                        scale(df$total_marbach_pval)))

# rename network id column
colnames(df)[1] <- 'network_id'

# sort by enrichment score and add a rank column
df <- df %>% arrange(desc(enrichment_score))
df$rank <- 1:nrow(df)

# show rank column at left
df <- df[,c(ncol(df), 1:(ncol(df) - 1))]
```
